### PR TITLE
test cases for sell form made

### PR DESCRIPTION
**Pull request by AmaarJ**
## Description

Test cases for the sell form constraints were made, tests also check if added new ticket information is displayed on profile page.

## Screenshot

None.

## Type of change
No changes to code.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass locally with my changes

*Please request review from all team members.*

### CODE REVIEW

**Review by aartisinghh — APPROVED** [review]
Looks really good!

**Review by aartisinghh — COMMENTED** [review]
is there a test for R4.2? the one for checking for 60 characters?

**Comment by aartisinghh** [comment]
> is there a test for R4.2? the one for checking for 60 characters?

Found it! Good job :)

**Review by lia-mason — APPROVED** [review]
Looks good to me!:)

**Pull request merged**
