### PR TITLE
Add Dockerfile and docker-compose.yml

### PR DESCRIPTION
**Pull request by lia-mason**
## Description

Added Dockerfile and docker-compose.yml files from https://github.com/CISC-CMPE-327/CI-Python/pull/9/files

## Screenshot

n/a

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] My changes generate no new warnings
- [] New and existing tests pass locally with my changes

*Please request review from all team members.*

### CODE REVIEW

**Review by AmaarJ — APPROVED** [review]
Thanks!

**Review by buchim1 — APPROVED** [review]
Looks good

**Review by AmaarJ — APPROVED** [review]
Amazing work!

**Review by AmaarJ — APPROVED** [review]
Wonderful!

**Pull request merged**
